# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultie" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "12c3caab8bacb4423e10d6ad7fe83fee75e17ec3d5f267e055192ed5c1b8f74e"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "84a3e581c8e3995dfa6f0a04385bd0861b55e0f9fc462cf49917cda6b90040dc"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2c1d5dcb66ab784dfb0d57f898d7dc3a2bb1217f655c01c57f2114470477150c"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9a1b0e628325c67e20bd072f629e90ebcf777370c01433e6402c0a00ea943f4"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vaultie"
  desc "A Kubie-like context switcher for multiple HashiCorp Vault instances."
  homepage "https://github.com/pacerino/vaultie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vaultie"]
    end
  end
  generate_completions_from_executable "vaultie", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
