# This file was generated by GoReleaser. DO NOT EDIT.
cask "vaultie" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "5e6e3e4b252609637df4244882865ad18d360c173cd159ea8af954be5b031d84"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6f63d1936690dcdb436995f014bc09103ac95f171251f5bcea7c53e74a8e9f53"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "07d9e0756c1f843363947f3c6da0ecc038018612e7c9c3288f7ebe2f6d4e4f69"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "13ecdb13a40c661a06d71be68668d8e17938063033bb32bb6abccae33737defa"
      url "https://github.com/Pacerino/vaultie/releases/download/v#{version}/vaultie_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vaultie"
  desc "A Kubie-like context switcher for multiple HashiCorp Vault instances."
  homepage "https://github.com/pacerino/vaultie"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vaultie"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vaultie"]
    end
  end
  generate_completions_from_executable "vaultie", "completion",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
